<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.dataease.plugin</groupId>
    <artifactId>oceanbase-oracle-backend</artifactId>
    <version>2.10.20</version>
    <packaging>jar</packaging>
    <name>DataEase OceanBase Oracle Datasource Plugin</name>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <dataease.version>2.10.20</dataease.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.dataease</groupId>
            <artifactId>extensions-datasource</artifactId>
            <version>${dataease.version}</version>
        </dependency>
        <dependency>
            <groupId>io.dataease</groupId>
            <artifactId>common</artifactId>
            <version>${dataease.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
        </resources>


        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-frontend-package-to-backend-jar</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/component</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/../extensions-ds-oceanbase-oracle-frontend-package/src/component</directory>
                                    <includes>
                                        <include>**/*</include>
                                    </includes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                            <overwrite>true</overwrite>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build></project>
